apiVersion: v1
kind: Namespace
metadata:
  name: na-ru-to-np
  labels:
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: sa-su-ke-np
  labels:
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: op-zo-ro-np
  labels:
    env: dev
